### PR TITLE
Feature: Id generation pattern customization

### LINKED ISSUE #2: Allow to customize the current id generation pattern
I'm currently using this extension in one proyect that uses the formatjs/enforce-id rule for ESLint with the [sha512:contenthash:base64:6] pattern, so when I add a <FormattedMessage /> this automatically throws an ESLint error due to ID incompatibility.

Some customization to the extension to change the current id pattern would help to prevents those errors.

### PR DESCRIPTION
**Pull request by KontrolG**
It does have a default configuration, as you requested, so everything still works as the same until the user change the configuration. 😋

This closes #2

### CODE REVIEW

**Comment by etaiklein** [comment]
Nice one! Ill test it out on monday. Can you also update the README to describe the new configuration options?

**Comment by KontrolG** [comment]
@etaiklein Thanks for the reply. Sure 😊

**Comment by KontrolG** [comment]
@etaiklein Done with the README.

**Comment by etaiklein** [comment]
I patched the request and I was eventually able to get it to work for both settings after running npm install from the local copy. 

I'm not sure how vscode extensions bundle node modules, so I moved the require for the new package inline into the function where it's used. That way the default works even if the node package somehow doesn't get installed. If you want to change the behavior there, you can look into compiling the package into the extension (see https://code.visualstudio.com/api/working-with-extensions/bundling-extension).

It also looked like your latest force-push clobbered the README changes so I added those back in as well.

edit: After testing the pushed update, it seems like node module packaging Just Works 👍

**Comment by etaiklein** [comment]
I've pushed version the new version! Let me know if you run into any issues.

If you find the extension useful, please leave a review on the marketplace: https://marketplace.visualstudio.com/items?itemName=etaiklein.formatted-message

**Comment by KontrolG** [comment]
> I patched the request and I was eventually able to get it to work for both settings after running npm install from the local copy.
> 
> I'm not sure how vscode extensions bundle node modules, so I moved the require for the new package inline into the function where it's used. That way the default works even if the node package somehow doesn't get installed. If you want to change the behavior there, you can look into compiling the package into the extension (see https://code.visualstudio.com/api/working-with-extensions/bundling-extension).
> 
> It also looked like your latest force-push clobbered the README changes so I added those back in as well.
> 
> edit: After testing the pushed update, it seems like node module packaging Just Works 👍

That one was clever (move the require call). Thanks again for the extension and for letting me contribute ❤

**Pull request merged**
